# Generated by Django 4.0.4 on 2022-05-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_persona_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField(default=0.0)),
            ],
        ),
    ]
